version: '3'

services:
  # MySQL
  db:
    image: mysql:5.7
    container_name: mysql_test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
    - 3305:3306
    networks:
    - base_app_network

  app:
    build: .
    ports:
    - 3000:3000
    networks:
    - base_app_network

volumes:
  test_db:
    external: false

networks:
  base_app_network:
    external: true